django/lecture3/hello/urls.py
from django.urls import path
from . import views

urlpatterns = [
  path("", views.index, name="index"),
  path("<str:name>", views.greet, name="greet"),
  path("swab", views.swab, name="swab"),
  path("jul", views.jul, name="jul")
]

django/lecture3/lecture3/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('hello/', include("hello.urls")),
    path('tasks/', include("tasks.urls")),
    path('newyear/', include("newyear.urls")),
]

django/lecture3/newyear/urls.py
from django.urls import path
from . import views

urlpatterns = [
  path("", views.index, name="index")
]

django/lecture3/tasks/urls.py
from django.urls import path

from . import views

app_name = "tasks"
urlpatterns = [
  path("", views.index, name="index"),
  path("add", views.add, name="add"),
]

django/lecture3/hello/models.py
from django.db import models

# Create your models here.

django/lecture3/newyear/models.py
from django.db import models

# Create your models here.

django/lecture3/tasks/models.py
from django.db import models

# Create your models here.

django/lecture3/hello/views.py
from django.http import HttpResponse
from django.shortcuts import render

# Create your views here.
def index(request):
    return render(request, "hello/index.html")

def swab(request):
    return HttpResponse("Hello Swab!")

def jul(request):
    return HttpResponse("Hello Jul!")

def greet(request, name):
    return render(request, "hello/greet.html" , {
        "name": name.capitalize()
    })

django/lecture3/newyear/views.py
import datetime
from django.shortcuts import render



# Create your views here.
def index(request):
    now = datetime.datetime.now()
    return render(request, "newyear/index.html", {
      "newyear": now.month == 1 and now.date == 1
    })

django/lecture3/tasks/views.py
from django import forms
from django.shortcuts import render

tasks = ["eat", "drink", "sleep"]

class NewTaskFrom(forms.Form):
    task = forms.CharField(label="New Task")


# Create your views here.
def index(request):
    return render(request, "tasks/index.html", {
        "tasks": tasks
    })

def add(request):
    return render(request, "tasks/add.html", {
        "form": NewTaskFrom()
    })

django/lecture3/hello/templates/hello/greet.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta charset="UTF-8">
  <meta name="viewport" content="device=width-device, initial-scale=1.0">
  <title>Hello</title>
</head>
<body>
  <h1>Hello, {{ name }}!</h1>
</body>
</html>

django/lecture3/hello/templates/hello/index.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta charset="UTF-8">
  <meta name="viewport" content="device=width-device, initial-scale=1.0">
  <title>Python</title>
</head>
<body>
  <h1>Hello Swabe!</h1>
  <h2>Let's start you journey in Python</h2>
</body>
</html>

django/lecture3/newyear/templates/newyear/index.html
{% load static%}

<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
  <link href="{% static 'newyear/styles.css'%}" rel="stylesheet">
</head>
<body>
  {% if newyear %}
      <h1>Yes</h1>
  {% else %}
      <h1>No</h1>
  {% endif %}
</body>
</html>

django/lecture3/tasks/templates/tasks/add.html
{% extends "tasks/layout.html" %}

{% block body %}
  <h1>Add Task</h1>
  <form action="{% url 'tasks:add' %}" method="post">
    {% csrf_token %}
    {{ form }}
    <!-- <input type="text" name="task"> -->
    <input type="submit">
  </form>

  <a href="{% url 'tasks:index' %}">View task</a>
{% endblock %}

django/lecture3/tasks/templates/tasks/index.html
{% extends "tasks/layout.html" %}

{% block body %}
  <h1>Test</h1>
  <ul>
    {% for tasks in tasks%}
        <li>{{ tasks }}</li>
    {% endfor %}
  </ul>

  <a href="{% url 'tasks:add' %}">Add task</a>
{% endblock %}

django/lecture3/tasks/templates/tasks/layout.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Task</title>
</head>
<body>
  {% block body %}

  {% endblock %}
</body>
</html>